{% set name = "rod" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rod-{{ version }}.tar.gz
  sha256: 34c907554fbfd93cb864c6c09fadf1c51526e8fadc3307aaea12b80503b61a68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - wheel
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - resolve-robotics-uri-py
    - python >=3.8
    - coloredlogs
    - mashumaro
    - numpy
    - packaging
    - scipy
    - xmltodict

test:
  imports:
    - rod
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ami-iit/rod
  summary: The ultimate Python tool for RObot Descriptions processing.
  dev_url: https://github.com/ami-iit/rod
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - flferretti
